language:
    bash

os:
    linux
    osx

before_install:
    sudo apt-get install tesseract-ocr tesseract-ocr-osd tesseract-ocr-eng ghostscript inotify-tools poppler-utils

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh

